FORMAT: 1A
HOST: http://movabletype.org

# Movable Type Data API v2
The Movable Type Data API is a REST interface to the Movable Type Content Management System.
The Data API is available for Movable Type Pro and Movable Type Advanced / Enterprise, Version 6.0 and higher.

# Group Assets

This is the Assets resource

Property Name | Type | Data Type | Database Column | Private | Read Only | Description
------------ | ------------- | ------------ | ------------ | ------------- | ------------ | ------------
id | value  | number | mt_asset.asset_id | Y |  | The ID of this asset.
label | value  | string | mt_asset.asset_label | | | The label of this asset.
mimeType | value | string | mt_asset.asset_mime_type | | Y | The MIME Type of this asset.
url | value | string | mt_asset.asset_url | | Y | The permalink URL of this asset.
filename | value | string | mt_asset.asset_filename | | Y | The filename of this asset that includes file extension.
description | value | string | mt_asset_asset_description | | | The desciption of this asset.
tags | ARRAY | string | | | | A list of tags associated with this asset.
blog | object | - | | | | The blog of this asset.
blog.id | value | number | mt_asset.asset_blog_id | | Y | The ID of the blog that contains this asset.
updatable | value | boolean | | | Y | <dl><dt>true</dt><dd>The user who accessed can update this asset.</dd><dt>false</dt><dd>The user who accessed cannot update this asset.</dd>
modifiedBy | Object | - | | | Y | The last modified user of this asset.
modifiedBy.id | value | number | mt_asset.asset_modified_by | Y | Y | The ID of last modified user.
modifiedBy.userpicUrl | value | string | | | Y | The URL of last modified user's userpic. The userpic will be made by UserpicThumbnailSize and UserpicAllowRect settings. If user does not set own userpic, will be returned empty string.
modifiedBy.displayName | value | string | | | Y | The display name of last modified user.
modifiedDate | value | iso 8601 datetime | mt_asset.asset_modified_on | | Y | The last modified time for this asset.
createdBy | Object | - | | | Y | The created user of this asset.
createdBy.id | value | number | mt_asset.asset_created_by | Y | Y | The ID of created user.
createdBy.userpicUrl | value | string | | | Y | The URL of created user's userpic. The userpic will be made by UserpicThumbnailSize and UserpicAllowRect settings. If user does not set own userpic, will be returned empty string.
cratedDate | value | iso 8601 datetime | mt_asset.asset_created_on | | Y | The created time for this asset.
type | value | string | mt_asset.asset_class | | Y | The type of this asset. The value will be returned localized value with DefaultLanguage.
class | value | string | mt_asset.asset_class | | | The type of this asset. This value is similar to 'type' attribute but this value is never localized.
FileExt | value | string | mt_asset.asset_file_ext | | Y | The file extension of this asset. eturns the file extension without the leading period.
parent | object | - | | | Y | The parent asset of this asset. If this asset is not a child of any assets, will be returned null.
parent.id | value | number | asset_parent | | | The ID of parent asset.
meta | object | - | | | Y | The meta information of this asset.
meta.imageHeight | value | number | | | Y | The height of this asset. If this asset has not height meta informatipn, will be returned null.
meta.imageWeight | value | number | | | Y | The weight of this asset. If this asset has not weight meta informatipn, will be returned null.
meta.fileSize | value | number | | | Y | The file size of this asset. If this asset is not file-based asset, will be returned null.

## Assets Colection [/sites/{site_id}/assets]

+ Parameters
    + site_id (required, number) ... The site ID.

### listBysite [GET]
+ Parameters
    + limit = `10` (optional, number) ... Maximum number of assets to retrieve.
    + offset = `0` (optional, number) ... 0-indexed offset.
    + class (optional string) ... The target asset class to retrieve. Available value is 'image', 'audio', 'video', 'file', also something added by any plugins. If you want to retrieve multiple class, specify the strings which separated by comma.
    + sortBy = `created_on` (option, string) ... hogehoge
    + sortOrder = `descend` (option, string) ... <dl><dt>descend</dt><dd>(default) Return assets in descending order. For the date, it means from newest to oldest.</dd><dt>ascend</dt><dd>Return assets in ascending order. For the date, it means from oldest to newset.    </dd></dl>
    + fields (optional, string) ... The field list to retrieve as part of the Assets resource. That list should be separated by comma. If this parameter is not specified, All fields will be returned.

<dl><dt>file_name</dt><dd>Sort by the filename of each assets.</dd><dt>created_by</dt><dd>Sort by the ID of user who created each assets. </dd><dt>created_on</dt><dd>(default) Sort by the created time of each assets.</dd></dl>

+ Response 200 (application/json)

        {
          "totalResults" : 1,
          "items" : [
            {
              "updatable" : false,
              "url" : "http://localhost/blog/20140917-2/images/0cf61aae.jpg",
              "id" : "1",
              "modifiedDate" : "2014-09-30T15:28:50+09:00",
              "parent" : null,
              "imageHeight" : 425,
              "blog" : {
                "id" : "1"
              },
              "description" : null,
              "tags" : [],
              "imageWidth" : 640,
              "fileSize" : "27930",
              "filename" : "0cf61aae.jpg",
              "createdUser" : {
                "userpicUrl" : null,
                "displayName" : "Yuji Takayama"
              },
              "type" : "画像",
              "mimeType" : "image/jpeg",
              "label" : "0cf61aae.jpg",
              "class" : "image",
              "createdDate" : "2014-09-30T15:28:50+09:00",
              "fileExtension" : "jpg"
            }
          ]
        }
