FORMAT: 1A
HOST: http://movabletype.org

# Movable Type Data API v2
The Movable Type Data API is a REST interface to the Movable Type Content Management System.
The Data API is available for Movable Type Pro and Movable Type Advanced / Enterprise, Version 6.0 and higher.

# Group Assets

First Header | Second Header | Third Header
------------ | ------------- | ------------
Content Cell | Content Cell  | Content Cell
Content Cell | Content Cell  | Content Cell

<table>
<thead>
<tr>
<th>Property Name </th>
<th> Type </th>
<th> Data Type </th>
<th> Database Column </th>
<th> Private </th>
<th> Read Only </th>
<th> Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>id </td>
<td> value </td>
<td> unsigned integer </td>
<td> mt_asset.asset_id </td>
<td> </td>
<td> Y </td>
<td> The ID of this asset.</td>
</tr>
<tr>
<td>label </td>
<td> value </td>
<td> string </td>
<td> mt_asset.asset_label </td>
<td> </td>
<td> </td>
<td> The label of this asset.</td>
</tr>
<tr>
<td>mimeType </td>
<td> value </td>
<td> string </td>
<td> mt_asset.asset_mime_type </td>
<td> </td>
<td> Y </td>
<td> The MIME Type of this asset.</td>
</tr>
<tr>
<td>url </td>
<td> value </td>
<td> string </td>
<td> mt_asset.asset_url </td>
<td> </td>
<td> Y </td>
<td> The permalink URL of this asset.</td>
</tr>
<tr>
<td> filename </td>
<td> value </td>
<td> string </td>
<td> mt_asset.asset_filename </td>
<td> </td>
<td> Y </td>
<td> The filename of this asset that includes file extension.</td>
</tr>
<tr>
<td>description </td>
<td> value </td>
<td> string </td>
<td> mt_asset_asset_description </td>
<td> </td>
<td> </td>
<td> The desciption of this asset.</td>
</tr>
<tr>
<td>tags </td>
<td> ARRAY </td>
<td> string </td>
<td> </td>
<td> </td>
<td> </td>
<td> A list of tags associated with this asset.</td>
</tr>
</tbody>
</table>

## Assets Colection [/sites/{site_id}/assets]

+ Parameters
    + site_id (required, number) ... The site ID.

### List all assets in the site [GET]
+ Parameters
    + limit = `10` (optional, number) ... Maximum number of assets to retrieve.

+ Response 200 (application/json)

        {
          "totalResults" : 1,
          "items" : [
            {
              "updatable" : false,
              "url" : "http://localhost/blog/20140917-2/images/0cf61aae.jpg",
              "id" : "1",
              "modifiedDate" : "2014-09-30T15:28:50+09:00",
              "parent" : null,
              "imageHeight" : 425,
              "blog" : {
                "id" : "1"
              },
              "description" : null,
              "tags" : [],
              "imageWidth" : 640,
              "fileSize" : "27930",
              "filename" : "0cf61aae.jpg",
              "createdUser" : {
                "userpicUrl" : null,
                "displayName" : "Yuji Takayama"
              },
              "type" : "画像",
              "mimeType" : "image/jpeg",
              "label" : "0cf61aae.jpg",
              "class" : "image",
              "createdDate" : "2014-09-30T15:28:50+09:00",
              "fileExtension" : "jpg"
            }
          ]
        }
