name: movabletype/mt-docs-data-api-reference
on:
  push:
    branches:
    - "**/*"
  pull_request:
  schedule:
  - cron: 0 8 * * *
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4.0.0
      with:
        cache: npm
        node-version: '20'
    - run: npm install
    - run: npm run redoc
